// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace Annual_faculty_promotions.WebUI.Areas.UserArea.Controllers
{
    public partial class RequestController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RequestController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Create()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Create);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult GetEducation()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetEducation);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult GetResearch()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetResearch);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult CreateEducationReasearch()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CreateEducationReasearch);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult CreateDissertation()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CreateDissertation);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult CreateScientificExecutive()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CreateScientificExecutive);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult CreateTechnology()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CreateTechnology);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult DeleteEducationReasearch()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteEducationReasearch);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult DeleteDissertation()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteDissertation);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult DeleteScientificExecutive()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteScientificExecutive);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult DeleteTechnology()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteTechnology);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult UpdateEducationReasearch()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UpdateEducationReasearch);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult UpdateDissertation()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UpdateDissertation);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult UpdateScientificExecutive()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UpdateScientificExecutive);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult UpdateTechnology()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UpdateTechnology);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult UploadAttachReasearch()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UploadAttachReasearch);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ListReaserchAttachForm()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ListReaserchAttachForm);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult destroyAttachResearch()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.destroyAttachResearch);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult GetReaserchAttach()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetReaserchAttach);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult GetDissertation()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetDissertation);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult GetScientificExecutive()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetScientificExecutive);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult GetTechnologies()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetTechnologies);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult CreateFurtherInformation()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CreateFurtherInformation);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public RequestController Actions { get { return MVC.UserArea.Request; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "UserArea";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Request";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Request";
        [GeneratedCode("T4MVC", "2.0")]
        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string Create = "Create";
            public readonly string GetEducation = "GetEducation";
            public readonly string GetResearch = "GetResearch";
            public readonly string GetEducationalResearchStatus = "GetEducationalResearchStatus";
            public readonly string GetPostPlan = "GetPostPlan";
            public readonly string GetTerm = "GetTerm";
            public readonly string GetGradeEducation = "GetGradeEducation";
            public readonly string GetTechnologyType = "GetTechnologyType";
            public readonly string CreateEducationReasearch = "CreateEducationReasearch";
            public readonly string CreateDissertation = "CreateDissertation";
            public readonly string CreateScientificExecutive = "CreateScientificExecutive";
            public readonly string CreateTechnology = "CreateTechnology";
            public readonly string DeleteEducationReasearch = "DeleteEducationReasearch";
            public readonly string DeleteDissertation = "DeleteDissertation";
            public readonly string DeleteScientificExecutive = "DeleteScientificExecutive";
            public readonly string DeleteTechnology = "DeleteTechnology";
            public readonly string UpdateEducationReasearch = "UpdateEducationReasearch";
            public readonly string UpdateDissertation = "UpdateDissertation";
            public readonly string UpdateScientificExecutive = "UpdateScientificExecutive";
            public readonly string UpdateTechnology = "UpdateTechnology";
            public readonly string UploadAttachReasearch = "UploadAttachReasearch";
            public readonly string ListReaserchAttachForm = "ListReaserchAttachForm";
            public readonly string destroyAttachResearch = "destroyAttachResearch";
            public readonly string GetReaserchAttach = "GetReaserchAttach";
            public readonly string GetDissertation = "GetDissertation";
            public readonly string GetScientificExecutive = "GetScientificExecutive";
            public readonly string GetTechnologies = "GetTechnologies";
            public readonly string CreateFurtherInformation = "CreateFurtherInformation";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string Create = "Create";
            public const string GetEducation = "GetEducation";
            public const string GetResearch = "GetResearch";
            public const string GetEducationalResearchStatus = "GetEducationalResearchStatus";
            public const string GetPostPlan = "GetPostPlan";
            public const string GetTerm = "GetTerm";
            public const string GetGradeEducation = "GetGradeEducation";
            public const string GetTechnologyType = "GetTechnologyType";
            public const string CreateEducationReasearch = "CreateEducationReasearch";
            public const string CreateDissertation = "CreateDissertation";
            public const string CreateScientificExecutive = "CreateScientificExecutive";
            public const string CreateTechnology = "CreateTechnology";
            public const string DeleteEducationReasearch = "DeleteEducationReasearch";
            public const string DeleteDissertation = "DeleteDissertation";
            public const string DeleteScientificExecutive = "DeleteScientificExecutive";
            public const string DeleteTechnology = "DeleteTechnology";
            public const string UpdateEducationReasearch = "UpdateEducationReasearch";
            public const string UpdateDissertation = "UpdateDissertation";
            public const string UpdateScientificExecutive = "UpdateScientificExecutive";
            public const string UpdateTechnology = "UpdateTechnology";
            public const string UploadAttachReasearch = "UploadAttachReasearch";
            public const string ListReaserchAttachForm = "ListReaserchAttachForm";
            public const string destroyAttachResearch = "destroyAttachResearch";
            public const string GetReaserchAttach = "GetReaserchAttach";
            public const string GetDissertation = "GetDissertation";
            public const string GetScientificExecutive = "GetScientificExecutive";
            public const string GetTechnologies = "GetTechnologies";
            public const string CreateFurtherInformation = "CreateFurtherInformation";
        }


        static readonly ActionParamsClass_Create s_params_Create = new ActionParamsClass_Create();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Create CreateParams { get { return s_params_Create; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Create
        {
            public readonly string model = "model";
            public readonly string officersStudyPhDUpload = "officersStudyPhDUpload";
            public readonly string typeOfPartTimeWorkNoconnectionOtherUniversityUpload = "typeOfPartTimeWorkNoconnectionOtherUniversityUpload";
            public readonly string typeOfPartTimeButEmployeesOtherUniversityUpload = "typeOfPartTimeButEmployeesOtherUniversityUpload";
            public readonly string typeOfFullTimeButRetiredUpload = "typeOfFullTimeButRetiredUpload";
            public readonly string typeOfFullTimeButNoRetiredUpload = "typeOfFullTimeButNoRetiredUpload";
            public readonly string passPhDPassaUpload = "passPhDPassaUpload";
            public readonly string takingSabbaticalUpload = "takingSabbaticalUpload";
            public readonly string freedmanOrCaptiveTypeUpload = "freedmanOrCaptiveTypeUpload";
            public readonly string fighterTypeUpload = "fighterTypeUpload";
            public readonly string veteranTypeUpload = "veteranTypeUpload";
        }
        static readonly ActionParamsClass_GetEducation s_params_GetEducation = new ActionParamsClass_GetEducation();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetEducation GetEducationParams { get { return s_params_GetEducation; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetEducation
        {
            public readonly string requestid = "requestid";
        }
        static readonly ActionParamsClass_GetResearch s_params_GetResearch = new ActionParamsClass_GetResearch();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetResearch GetResearchParams { get { return s_params_GetResearch; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetResearch
        {
            public readonly string requestid = "requestid";
        }
        static readonly ActionParamsClass_CreateEducationReasearch s_params_CreateEducationReasearch = new ActionParamsClass_CreateEducationReasearch();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_CreateEducationReasearch CreateEducationReasearchParams { get { return s_params_CreateEducationReasearch; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_CreateEducationReasearch
        {
            public readonly string educationalResearch = "educationalResearch";
        }
        static readonly ActionParamsClass_CreateDissertation s_params_CreateDissertation = new ActionParamsClass_CreateDissertation();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_CreateDissertation CreateDissertationParams { get { return s_params_CreateDissertation; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_CreateDissertation
        {
            public readonly string dissertation = "dissertation";
        }
        static readonly ActionParamsClass_CreateScientificExecutive s_params_CreateScientificExecutive = new ActionParamsClass_CreateScientificExecutive();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_CreateScientificExecutive CreateScientificExecutiveParams { get { return s_params_CreateScientificExecutive; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_CreateScientificExecutive
        {
            public readonly string scientificExecutive = "scientificExecutive";
        }
        static readonly ActionParamsClass_CreateTechnology s_params_CreateTechnology = new ActionParamsClass_CreateTechnology();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_CreateTechnology CreateTechnologyParams { get { return s_params_CreateTechnology; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_CreateTechnology
        {
            public readonly string technology = "technology";
        }
        static readonly ActionParamsClass_DeleteEducationReasearch s_params_DeleteEducationReasearch = new ActionParamsClass_DeleteEducationReasearch();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DeleteEducationReasearch DeleteEducationReasearchParams { get { return s_params_DeleteEducationReasearch; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DeleteEducationReasearch
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_DeleteDissertation s_params_DeleteDissertation = new ActionParamsClass_DeleteDissertation();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DeleteDissertation DeleteDissertationParams { get { return s_params_DeleteDissertation; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DeleteDissertation
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_DeleteScientificExecutive s_params_DeleteScientificExecutive = new ActionParamsClass_DeleteScientificExecutive();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DeleteScientificExecutive DeleteScientificExecutiveParams { get { return s_params_DeleteScientificExecutive; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DeleteScientificExecutive
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_DeleteTechnology s_params_DeleteTechnology = new ActionParamsClass_DeleteTechnology();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DeleteTechnology DeleteTechnologyParams { get { return s_params_DeleteTechnology; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DeleteTechnology
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_UpdateEducationReasearch s_params_UpdateEducationReasearch = new ActionParamsClass_UpdateEducationReasearch();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_UpdateEducationReasearch UpdateEducationReasearchParams { get { return s_params_UpdateEducationReasearch; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_UpdateEducationReasearch
        {
            public readonly string educationalResearch = "educationalResearch";
        }
        static readonly ActionParamsClass_UpdateDissertation s_params_UpdateDissertation = new ActionParamsClass_UpdateDissertation();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_UpdateDissertation UpdateDissertationParams { get { return s_params_UpdateDissertation; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_UpdateDissertation
        {
            public readonly string dissertation = "dissertation";
        }
        static readonly ActionParamsClass_UpdateScientificExecutive s_params_UpdateScientificExecutive = new ActionParamsClass_UpdateScientificExecutive();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_UpdateScientificExecutive UpdateScientificExecutiveParams { get { return s_params_UpdateScientificExecutive; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_UpdateScientificExecutive
        {
            public readonly string scientificExecutive = "scientificExecutive";
        }
        static readonly ActionParamsClass_UpdateTechnology s_params_UpdateTechnology = new ActionParamsClass_UpdateTechnology();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_UpdateTechnology UpdateTechnologyParams { get { return s_params_UpdateTechnology; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_UpdateTechnology
        {
            public readonly string technology = "technology";
        }
        static readonly ActionParamsClass_UploadAttachReasearch s_params_UploadAttachReasearch = new ActionParamsClass_UploadAttachReasearch();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_UploadAttachReasearch UploadAttachReasearchParams { get { return s_params_UploadAttachReasearch; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_UploadAttachReasearch
        {
            public readonly string reaserchId = "reaserchId";
            public readonly string chunk = "chunk";
            public readonly string name = "name";
        }
        static readonly ActionParamsClass_ListReaserchAttachForm s_params_ListReaserchAttachForm = new ActionParamsClass_ListReaserchAttachForm();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ListReaserchAttachForm ListReaserchAttachFormParams { get { return s_params_ListReaserchAttachForm; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ListReaserchAttachForm
        {
            public readonly string researchId = "researchId";
        }
        static readonly ActionParamsClass_destroyAttachResearch s_params_destroyAttachResearch = new ActionParamsClass_destroyAttachResearch();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_destroyAttachResearch destroyAttachResearchParams { get { return s_params_destroyAttachResearch; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_destroyAttachResearch
        {
            public readonly string researchAttachId = "researchAttachId";
        }
        static readonly ActionParamsClass_GetReaserchAttach s_params_GetReaserchAttach = new ActionParamsClass_GetReaserchAttach();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetReaserchAttach GetReaserchAttachParams { get { return s_params_GetReaserchAttach; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetReaserchAttach
        {
            public readonly string researchId = "researchId";
        }
        static readonly ActionParamsClass_GetDissertation s_params_GetDissertation = new ActionParamsClass_GetDissertation();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetDissertation GetDissertationParams { get { return s_params_GetDissertation; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetDissertation
        {
            public readonly string requestId = "requestId";
        }
        static readonly ActionParamsClass_GetScientificExecutive s_params_GetScientificExecutive = new ActionParamsClass_GetScientificExecutive();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetScientificExecutive GetScientificExecutiveParams { get { return s_params_GetScientificExecutive; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetScientificExecutive
        {
            public readonly string requestid = "requestid";
        }
        static readonly ActionParamsClass_GetTechnologies s_params_GetTechnologies = new ActionParamsClass_GetTechnologies();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetTechnologies GetTechnologiesParams { get { return s_params_GetTechnologies; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetTechnologies
        {
            public readonly string requestId = "requestId";
        }
        static readonly ActionParamsClass_CreateFurtherInformation s_params_CreateFurtherInformation = new ActionParamsClass_CreateFurtherInformation();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_CreateFurtherInformation CreateFurtherInformationParams { get { return s_params_CreateFurtherInformation; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_CreateFurtherInformation
        {
            public readonly string furtherInformation = "furtherInformation";
            public readonly string officersStudyPhDUpload = "officersStudyPhDUpload";
            public readonly string typeOfPartTimeWorkNoconnectionOtherUniversityUpload = "typeOfPartTimeWorkNoconnectionOtherUniversityUpload";
            public readonly string typeOfPartTimeButEmployeesOtherUniversityUpload = "typeOfPartTimeButEmployeesOtherUniversityUpload";
            public readonly string typeOfFullTimeButRetiredUpload = "typeOfFullTimeButRetiredUpload";
            public readonly string typeOfFullTimeButNoRetired = "typeOfFullTimeButNoRetired";
            public readonly string passPhDPassaUpload = "passPhDPassaUpload";
            public readonly string takingSabbaticalUpload = "takingSabbaticalUpload";
            public readonly string freedmanOrCaptiveTypeUpload = "freedmanOrCaptiveTypeUpload";
            public readonly string fighterTypeUpload = "fighterTypeUpload";
            public readonly string veteranTypeUpload = "veteranTypeUpload";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _AttachReaserch = "_AttachReaserch";
                public readonly string _CreateFurtherInformation = "_CreateFurtherInformation";
                public readonly string _listReaserchAttach = "_listReaserchAttach";
                public readonly string Index = "Index";
            }
            public readonly string _AttachReaserch = "~/Areas/UserArea/Views/Request/_AttachReaserch.cshtml";
            public readonly string _CreateFurtherInformation = "~/Areas/UserArea/Views/Request/_CreateFurtherInformation.cshtml";
            public readonly string _listReaserchAttach = "~/Areas/UserArea/Views/Request/_listReaserchAttach.cshtml";
            public readonly string Index = "~/Areas/UserArea/Views/Request/Index.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_RequestController : Annual_faculty_promotions.WebUI.Areas.UserArea.Controllers.RequestController
    {
        public T4MVC_RequestController() : base(Dummy.Instance) { }

        [NonAction]
        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Index()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            IndexOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void CreateOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Annual_faculty_promotions.WebUI.Areas.UserArea.Models.AddRequestViewModel model, System.Collections.Generic.IEnumerable<System.Web.HttpPostedFileBase> officersStudyPhDUpload, System.Collections.Generic.IEnumerable<System.Web.HttpPostedFileBase> typeOfPartTimeWorkNoconnectionOtherUniversityUpload, System.Collections.Generic.IEnumerable<System.Web.HttpPostedFileBase> typeOfPartTimeButEmployeesOtherUniversityUpload, System.Collections.Generic.IEnumerable<System.Web.HttpPostedFileBase> typeOfFullTimeButRetiredUpload, System.Collections.Generic.IEnumerable<System.Web.HttpPostedFileBase> typeOfFullTimeButNoRetiredUpload, System.Collections.Generic.IEnumerable<System.Web.HttpPostedFileBase> passPhDPassaUpload, System.Collections.Generic.IEnumerable<System.Web.HttpPostedFileBase> takingSabbaticalUpload, System.Collections.Generic.IEnumerable<System.Web.HttpPostedFileBase> freedmanOrCaptiveTypeUpload, System.Collections.Generic.IEnumerable<System.Web.HttpPostedFileBase> fighterTypeUpload, System.Collections.Generic.IEnumerable<System.Web.HttpPostedFileBase> veteranTypeUpload);

        [NonAction]
        public override System.Web.Mvc.ActionResult Create(Annual_faculty_promotions.WebUI.Areas.UserArea.Models.AddRequestViewModel model, System.Collections.Generic.IEnumerable<System.Web.HttpPostedFileBase> officersStudyPhDUpload, System.Collections.Generic.IEnumerable<System.Web.HttpPostedFileBase> typeOfPartTimeWorkNoconnectionOtherUniversityUpload, System.Collections.Generic.IEnumerable<System.Web.HttpPostedFileBase> typeOfPartTimeButEmployeesOtherUniversityUpload, System.Collections.Generic.IEnumerable<System.Web.HttpPostedFileBase> typeOfFullTimeButRetiredUpload, System.Collections.Generic.IEnumerable<System.Web.HttpPostedFileBase> typeOfFullTimeButNoRetiredUpload, System.Collections.Generic.IEnumerable<System.Web.HttpPostedFileBase> passPhDPassaUpload, System.Collections.Generic.IEnumerable<System.Web.HttpPostedFileBase> takingSabbaticalUpload, System.Collections.Generic.IEnumerable<System.Web.HttpPostedFileBase> freedmanOrCaptiveTypeUpload, System.Collections.Generic.IEnumerable<System.Web.HttpPostedFileBase> fighterTypeUpload, System.Collections.Generic.IEnumerable<System.Web.HttpPostedFileBase> veteranTypeUpload)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Create);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "officersStudyPhDUpload", officersStudyPhDUpload);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "typeOfPartTimeWorkNoconnectionOtherUniversityUpload", typeOfPartTimeWorkNoconnectionOtherUniversityUpload);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "typeOfPartTimeButEmployeesOtherUniversityUpload", typeOfPartTimeButEmployeesOtherUniversityUpload);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "typeOfFullTimeButRetiredUpload", typeOfFullTimeButRetiredUpload);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "typeOfFullTimeButNoRetiredUpload", typeOfFullTimeButNoRetiredUpload);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "passPhDPassaUpload", passPhDPassaUpload);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "takingSabbaticalUpload", takingSabbaticalUpload);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "freedmanOrCaptiveTypeUpload", freedmanOrCaptiveTypeUpload);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "fighterTypeUpload", fighterTypeUpload);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "veteranTypeUpload", veteranTypeUpload);
            CreateOverride(callInfo, model, officersStudyPhDUpload, typeOfPartTimeWorkNoconnectionOtherUniversityUpload, typeOfPartTimeButEmployeesOtherUniversityUpload, typeOfFullTimeButRetiredUpload, typeOfFullTimeButNoRetiredUpload, passPhDPassaUpload, takingSabbaticalUpload, freedmanOrCaptiveTypeUpload, fighterTypeUpload, veteranTypeUpload);
            return callInfo;
        }

        [NonAction]
        partial void GetEducationOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, long requestid);

        [NonAction]
        public override System.Web.Mvc.ActionResult GetEducation(long requestid)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetEducation);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "requestid", requestid);
            GetEducationOverride(callInfo, requestid);
            return callInfo;
        }

        [NonAction]
        partial void GetResearchOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, long requestid);

        [NonAction]
        public override System.Web.Mvc.ActionResult GetResearch(long requestid)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetResearch);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "requestid", requestid);
            GetResearchOverride(callInfo, requestid);
            return callInfo;
        }

        [NonAction]
        partial void GetEducationalResearchStatusOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult GetEducationalResearchStatus()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetEducationalResearchStatus);
            GetEducationalResearchStatusOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void GetPostPlanOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult GetPostPlan()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetPostPlan);
            GetPostPlanOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void GetTermOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult GetTerm()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetTerm);
            GetTermOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void GetGradeEducationOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult GetGradeEducation()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetGradeEducation);
            GetGradeEducationOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void GetTechnologyTypeOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult GetTechnologyType()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetTechnologyType);
            GetTechnologyTypeOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void CreateEducationReasearchOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Annual_faculty_promotions.Core.Domain.EducationalResearch educationalResearch);

        [NonAction]
        public override System.Web.Mvc.ActionResult CreateEducationReasearch(Annual_faculty_promotions.Core.Domain.EducationalResearch educationalResearch)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CreateEducationReasearch);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "educationalResearch", educationalResearch);
            CreateEducationReasearchOverride(callInfo, educationalResearch);
            return callInfo;
        }

        [NonAction]
        partial void CreateDissertationOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Annual_faculty_promotions.Core.Domain.Dissertation dissertation);

        [NonAction]
        public override System.Web.Mvc.ActionResult CreateDissertation(Annual_faculty_promotions.Core.Domain.Dissertation dissertation)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CreateDissertation);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "dissertation", dissertation);
            CreateDissertationOverride(callInfo, dissertation);
            return callInfo;
        }

        [NonAction]
        partial void CreateScientificExecutiveOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Annual_faculty_promotions.Core.Domain.ScientificExecutive scientificExecutive);

        [NonAction]
        public override System.Web.Mvc.ActionResult CreateScientificExecutive(Annual_faculty_promotions.Core.Domain.ScientificExecutive scientificExecutive)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CreateScientificExecutive);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "scientificExecutive", scientificExecutive);
            CreateScientificExecutiveOverride(callInfo, scientificExecutive);
            return callInfo;
        }

        [NonAction]
        partial void CreateTechnologyOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Annual_faculty_promotions.Core.Domain.Technology technology);

        [NonAction]
        public override System.Web.Mvc.ActionResult CreateTechnology(Annual_faculty_promotions.Core.Domain.Technology technology)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CreateTechnology);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "technology", technology);
            CreateTechnologyOverride(callInfo, technology);
            return callInfo;
        }

        [NonAction]
        partial void DeleteEducationReasearchOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.ActionResult DeleteEducationReasearch(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteEducationReasearch);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            DeleteEducationReasearchOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void DeleteDissertationOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.ActionResult DeleteDissertation(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteDissertation);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            DeleteDissertationOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void DeleteScientificExecutiveOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.ActionResult DeleteScientificExecutive(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteScientificExecutive);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            DeleteScientificExecutiveOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void DeleteTechnologyOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.ActionResult DeleteTechnology(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteTechnology);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            DeleteTechnologyOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void UpdateEducationReasearchOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Annual_faculty_promotions.Core.Domain.EducationalResearch educationalResearch);

        [NonAction]
        public override System.Web.Mvc.ActionResult UpdateEducationReasearch(Annual_faculty_promotions.Core.Domain.EducationalResearch educationalResearch)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UpdateEducationReasearch);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "educationalResearch", educationalResearch);
            UpdateEducationReasearchOverride(callInfo, educationalResearch);
            return callInfo;
        }

        [NonAction]
        partial void UpdateDissertationOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Annual_faculty_promotions.Core.Domain.Dissertation dissertation);

        [NonAction]
        public override System.Web.Mvc.ActionResult UpdateDissertation(Annual_faculty_promotions.Core.Domain.Dissertation dissertation)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UpdateDissertation);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "dissertation", dissertation);
            UpdateDissertationOverride(callInfo, dissertation);
            return callInfo;
        }

        [NonAction]
        partial void UpdateScientificExecutiveOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Annual_faculty_promotions.Core.Domain.ScientificExecutive scientificExecutive);

        [NonAction]
        public override System.Web.Mvc.ActionResult UpdateScientificExecutive(Annual_faculty_promotions.Core.Domain.ScientificExecutive scientificExecutive)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UpdateScientificExecutive);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "scientificExecutive", scientificExecutive);
            UpdateScientificExecutiveOverride(callInfo, scientificExecutive);
            return callInfo;
        }

        [NonAction]
        partial void UpdateTechnologyOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Annual_faculty_promotions.Core.Domain.Technology technology);

        [NonAction]
        public override System.Web.Mvc.ActionResult UpdateTechnology(Annual_faculty_promotions.Core.Domain.Technology technology)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UpdateTechnology);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "technology", technology);
            UpdateTechnologyOverride(callInfo, technology);
            return callInfo;
        }

        [NonAction]
        partial void UploadAttachReasearchOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int reaserchId);

        [NonAction]
        public override System.Web.Mvc.ActionResult UploadAttachReasearch(int reaserchId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UploadAttachReasearch);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "reaserchId", reaserchId);
            UploadAttachReasearchOverride(callInfo, reaserchId);
            return callInfo;
        }

        [NonAction]
        partial void UploadAttachReasearchOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int? chunk, string name, int reaserchId);

        [NonAction]
        public override System.Web.Mvc.ActionResult UploadAttachReasearch(int? chunk, string name, int reaserchId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UploadAttachReasearch);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "chunk", chunk);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "name", name);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "reaserchId", reaserchId);
            UploadAttachReasearchOverride(callInfo, chunk, name, reaserchId);
            return callInfo;
        }

        [NonAction]
        partial void ListReaserchAttachFormOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int researchId);

        [NonAction]
        public override System.Web.Mvc.ActionResult ListReaserchAttachForm(int researchId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ListReaserchAttachForm);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "researchId", researchId);
            ListReaserchAttachFormOverride(callInfo, researchId);
            return callInfo;
        }

        [NonAction]
        partial void destroyAttachResearchOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, long researchAttachId);

        [NonAction]
        public override System.Web.Mvc.ActionResult destroyAttachResearch(long researchAttachId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.destroyAttachResearch);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "researchAttachId", researchAttachId);
            destroyAttachResearchOverride(callInfo, researchAttachId);
            return callInfo;
        }

        [NonAction]
        partial void GetReaserchAttachOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int researchId);

        [NonAction]
        public override System.Web.Mvc.ActionResult GetReaserchAttach(int researchId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetReaserchAttach);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "researchId", researchId);
            GetReaserchAttachOverride(callInfo, researchId);
            return callInfo;
        }

        [NonAction]
        partial void GetDissertationOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int requestId);

        [NonAction]
        public override System.Web.Mvc.ActionResult GetDissertation(int requestId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetDissertation);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "requestId", requestId);
            GetDissertationOverride(callInfo, requestId);
            return callInfo;
        }

        [NonAction]
        partial void GetScientificExecutiveOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, long requestid);

        [NonAction]
        public override System.Web.Mvc.ActionResult GetScientificExecutive(long requestid)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetScientificExecutive);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "requestid", requestid);
            GetScientificExecutiveOverride(callInfo, requestid);
            return callInfo;
        }

        [NonAction]
        partial void GetTechnologiesOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int requestId);

        [NonAction]
        public override System.Web.Mvc.ActionResult GetTechnologies(int requestId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetTechnologies);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "requestId", requestId);
            GetTechnologiesOverride(callInfo, requestId);
            return callInfo;
        }

        [NonAction]
        partial void CreateFurtherInformationOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Annual_faculty_promotions.Core.Domain.FurtherInformation furtherInformation, System.Collections.Generic.IEnumerable<System.Web.HttpPostedFileBase> officersStudyPhDUpload, System.Collections.Generic.IEnumerable<System.Web.HttpPostedFileBase> typeOfPartTimeWorkNoconnectionOtherUniversityUpload, System.Collections.Generic.IEnumerable<System.Web.HttpPostedFileBase> typeOfPartTimeButEmployeesOtherUniversityUpload, System.Collections.Generic.IEnumerable<System.Web.HttpPostedFileBase> typeOfFullTimeButRetiredUpload, System.Collections.Generic.IEnumerable<System.Web.HttpPostedFileBase> typeOfFullTimeButNoRetired, System.Collections.Generic.IEnumerable<System.Web.HttpPostedFileBase> passPhDPassaUpload, System.Collections.Generic.IEnumerable<System.Web.HttpPostedFileBase> takingSabbaticalUpload, System.Collections.Generic.IEnumerable<System.Web.HttpPostedFileBase> freedmanOrCaptiveTypeUpload, System.Collections.Generic.IEnumerable<System.Web.HttpPostedFileBase> fighterTypeUpload, System.Collections.Generic.IEnumerable<System.Web.HttpPostedFileBase> veteranTypeUpload);

        [NonAction]
        public override System.Web.Mvc.ActionResult CreateFurtherInformation(Annual_faculty_promotions.Core.Domain.FurtherInformation furtherInformation, System.Collections.Generic.IEnumerable<System.Web.HttpPostedFileBase> officersStudyPhDUpload, System.Collections.Generic.IEnumerable<System.Web.HttpPostedFileBase> typeOfPartTimeWorkNoconnectionOtherUniversityUpload, System.Collections.Generic.IEnumerable<System.Web.HttpPostedFileBase> typeOfPartTimeButEmployeesOtherUniversityUpload, System.Collections.Generic.IEnumerable<System.Web.HttpPostedFileBase> typeOfFullTimeButRetiredUpload, System.Collections.Generic.IEnumerable<System.Web.HttpPostedFileBase> typeOfFullTimeButNoRetired, System.Collections.Generic.IEnumerable<System.Web.HttpPostedFileBase> passPhDPassaUpload, System.Collections.Generic.IEnumerable<System.Web.HttpPostedFileBase> takingSabbaticalUpload, System.Collections.Generic.IEnumerable<System.Web.HttpPostedFileBase> freedmanOrCaptiveTypeUpload, System.Collections.Generic.IEnumerable<System.Web.HttpPostedFileBase> fighterTypeUpload, System.Collections.Generic.IEnumerable<System.Web.HttpPostedFileBase> veteranTypeUpload)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CreateFurtherInformation);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "furtherInformation", furtherInformation);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "officersStudyPhDUpload", officersStudyPhDUpload);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "typeOfPartTimeWorkNoconnectionOtherUniversityUpload", typeOfPartTimeWorkNoconnectionOtherUniversityUpload);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "typeOfPartTimeButEmployeesOtherUniversityUpload", typeOfPartTimeButEmployeesOtherUniversityUpload);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "typeOfFullTimeButRetiredUpload", typeOfFullTimeButRetiredUpload);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "typeOfFullTimeButNoRetired", typeOfFullTimeButNoRetired);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "passPhDPassaUpload", passPhDPassaUpload);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "takingSabbaticalUpload", takingSabbaticalUpload);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "freedmanOrCaptiveTypeUpload", freedmanOrCaptiveTypeUpload);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "fighterTypeUpload", fighterTypeUpload);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "veteranTypeUpload", veteranTypeUpload);
            CreateFurtherInformationOverride(callInfo, furtherInformation, officersStudyPhDUpload, typeOfPartTimeWorkNoconnectionOtherUniversityUpload, typeOfPartTimeButEmployeesOtherUniversityUpload, typeOfFullTimeButRetiredUpload, typeOfFullTimeButNoRetired, passPhDPassaUpload, takingSabbaticalUpload, freedmanOrCaptiveTypeUpload, fighterTypeUpload, veteranTypeUpload);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
