// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace Annual_faculty_promotions.WebUI.Areas.UserArea.Controllers
{
    public partial class ProfileController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected ProfileController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult SendMessage()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SendMessage);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult RenderComboRecievers()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.RenderComboRecievers);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult UpdateProfile()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UpdateProfile);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ProfileController Actions { get { return MVC.UserArea.Profile; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "UserArea";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Profile";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Profile";
        [GeneratedCode("T4MVC", "2.0")]
        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string Activity = "Activity";
            public readonly string SendMessage = "SendMessage";
            public readonly string RenderParialMessage = "RenderParialMessage";
            public readonly string RenderMessagesList = "RenderMessagesList";
            public readonly string GetMessages = "GetMessages";
            public readonly string RenderComboRecievers = "RenderComboRecievers";
            public readonly string RenderPartialEditProfile = "RenderPartialEditProfile";
            public readonly string UpdateProfile = "UpdateProfile";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string Activity = "Activity";
            public const string SendMessage = "SendMessage";
            public const string RenderParialMessage = "RenderParialMessage";
            public const string RenderMessagesList = "RenderMessagesList";
            public const string GetMessages = "GetMessages";
            public const string RenderComboRecievers = "RenderComboRecievers";
            public const string RenderPartialEditProfile = "RenderPartialEditProfile";
            public const string UpdateProfile = "UpdateProfile";
        }


        static readonly ActionParamsClass_SendMessage s_params_SendMessage = new ActionParamsClass_SendMessage();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SendMessage SendMessageParams { get { return s_params_SendMessage; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SendMessage
        {
            public readonly string text = "text";
            public readonly string enumRoles = "enumRoles";
            public readonly string recievers = "recievers";
        }
        static readonly ActionParamsClass_RenderMessagesList s_params_RenderMessagesList = new ActionParamsClass_RenderMessagesList();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_RenderMessagesList RenderMessagesListParams { get { return s_params_RenderMessagesList; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_RenderMessagesList
        {
            public readonly string page = "page";
            public readonly string pageSize = "pageSize";
        }
        static readonly ActionParamsClass_GetMessages s_params_GetMessages = new ActionParamsClass_GetMessages();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetMessages GetMessagesParams { get { return s_params_GetMessages; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetMessages
        {
            public readonly string page = "page";
            public readonly string pageSize = "pageSize";
        }
        static readonly ActionParamsClass_RenderComboRecievers s_params_RenderComboRecievers = new ActionParamsClass_RenderComboRecievers();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_RenderComboRecievers RenderComboRecieversParams { get { return s_params_RenderComboRecievers; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_RenderComboRecievers
        {
            public readonly string enumvalue = "enumvalue";
        }
        static readonly ActionParamsClass_UpdateProfile s_params_UpdateProfile = new ActionParamsClass_UpdateProfile();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_UpdateProfile UpdateProfileParams { get { return s_params_UpdateProfile; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_UpdateProfile
        {
            public readonly string profile = "profile";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _Activity = "_Activity";
                public readonly string _ComboRecievers = "_ComboRecievers";
                public readonly string _EditProfile = "_EditProfile";
                public readonly string _Index = "_Index";
                public readonly string _Messages = "_Messages";
                public readonly string _MessagesList = "_MessagesList";
                public readonly string Index = "Index";
            }
            public readonly string _Activity = "~/Areas/UserArea/Views/Profile/_Activity.cshtml";
            public readonly string _ComboRecievers = "~/Areas/UserArea/Views/Profile/_ComboRecievers.cshtml";
            public readonly string _EditProfile = "~/Areas/UserArea/Views/Profile/_EditProfile.cshtml";
            public readonly string _Index = "~/Areas/UserArea/Views/Profile/_Index.cshtml";
            public readonly string _Messages = "~/Areas/UserArea/Views/Profile/_Messages.cshtml";
            public readonly string _MessagesList = "~/Areas/UserArea/Views/Profile/_MessagesList.cshtml";
            public readonly string Index = "~/Areas/UserArea/Views/Profile/Index.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_ProfileController : Annual_faculty_promotions.WebUI.Areas.UserArea.Controllers.ProfileController
    {
        public T4MVC_ProfileController() : base(Dummy.Instance) { }

        [NonAction]
        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Index()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            IndexOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void ActivityOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Activity()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Activity);
            ActivityOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void SendMessageOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string text, int enumRoles, int recievers);

        [NonAction]
        public override System.Web.Mvc.ActionResult SendMessage(string text, int enumRoles, int recievers)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SendMessage);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "text", text);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "enumRoles", enumRoles);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "recievers", recievers);
            SendMessageOverride(callInfo, text, enumRoles, recievers);
            return callInfo;
        }

        [NonAction]
        partial void RenderParialMessageOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult RenderParialMessage()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.RenderParialMessage);
            RenderParialMessageOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void RenderMessagesListOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int page, int pageSize);

        [NonAction]
        public override System.Web.Mvc.ActionResult RenderMessagesList(int page, int pageSize)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.RenderMessagesList);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "page", page);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "pageSize", pageSize);
            RenderMessagesListOverride(callInfo, page, pageSize);
            return callInfo;
        }

        [NonAction]
        partial void GetMessagesOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int page, int pageSize);

        [NonAction]
        public override System.Web.Mvc.ActionResult GetMessages(int page, int pageSize)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetMessages);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "page", page);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "pageSize", pageSize);
            GetMessagesOverride(callInfo, page, pageSize);
            return callInfo;
        }

        [NonAction]
        partial void RenderComboRecieversOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int enumvalue);

        [NonAction]
        public override System.Web.Mvc.ActionResult RenderComboRecievers(int enumvalue)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.RenderComboRecievers);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "enumvalue", enumvalue);
            RenderComboRecieversOverride(callInfo, enumvalue);
            return callInfo;
        }

        [NonAction]
        partial void RenderPartialEditProfileOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult RenderPartialEditProfile()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.RenderPartialEditProfile);
            RenderPartialEditProfileOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void UpdateProfileOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Annual_faculty_promotions.Core.Domain.User.Profile profile);

        [NonAction]
        public override System.Web.Mvc.ActionResult UpdateProfile(Annual_faculty_promotions.Core.Domain.User.Profile profile)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UpdateProfile);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "profile", profile);
            UpdateProfileOverride(callInfo, profile);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
